name: Deploy

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build app
      uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: 'hyoo/habhub'
    
    - uses: nin-jin/blazing-fast-gh-pages-deploy@master
      if: github.ref == 'refs/heads/master'
      with:
        site-directory: 'hyoo/habhub/-'
